# fly.toml app configuration file generated for serverspotify-long-shape-3962 on 2024-04-22T17:00:05+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'serverspotify-long-shape-3962'
primary_region = 'mad'

[build]
  image = 'flyio/hellofly:latest'

[http_service]
  internal_port = 3005
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
